-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.pick_up_points
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    post_code integer NOT NULL,
    city character varying NOT NULL,
    street character varying NOT NULL,
    building integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    surname character varying NOT NULL,
    name character varying NOT NULL,
    patronymic character varying NOT NULL,
    login character varying NOT NULL,
    password character varying NOT NULL,
    user_role integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.roles
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    name character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_units
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    name character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_providers
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    name character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_producers
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    name character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_categories
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    name character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.products
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    article character varying NOT NULL,
    name character varying NOT NULL,
    unit_id integer NOT NULL,
    price integer NOT NULL,
    provider_id integer NOT NULL,
    producer_id integer NOT NULL,
    category_id integer NOT NULL,
    discount integer NOT NULL,
    amount_in_stock integer NOT NULL,
    description character varying NOT NULL,
    photo character varying,
    CONSTRAINT id_unique PRIMARY KEY (id),
    CONSTRAINT id_unique UNIQUE (id)
);

CREATE TABLE IF NOT EXISTS public.orders
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    date_creation date NOT NULL,
    date_delivery date NOT NULL,
    pick_up_point_id integer NOT NULL,
    user_id integer NOT NULL,
    receipt_code integer NOT NULL,
    status_id integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.product_in_order
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    order_id integer NOT NULL,
    product_id integer NOT NULL,
    amount integer NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.order_statuses
(
    id integer NOT NULL GENERATED ALWAYS AS IDENTITY,
    name character varying NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.users
    ADD FOREIGN KEY (user_role)
    REFERENCES public.roles (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.products
    ADD FOREIGN KEY (provider_id)
    REFERENCES public.product_providers (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.products
    ADD FOREIGN KEY (producer_id)
    REFERENCES public.product_producers (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.products
    ADD FOREIGN KEY (category_id)
    REFERENCES public.product_categories (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.products
    ADD FOREIGN KEY (unit_id)
    REFERENCES public.product_units (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.orders
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.orders
    ADD FOREIGN KEY (pick_up_point_id)
    REFERENCES public.pick_up_points (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.orders
    ADD FOREIGN KEY (status_id)
    REFERENCES public.order_statuses (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.product_in_order
    ADD FOREIGN KEY (product_id)
    REFERENCES public.products (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;


ALTER TABLE IF EXISTS public.product_in_order
    ADD FOREIGN KEY (order_id)
    REFERENCES public.orders (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE CASCADE
    NOT VALID;

END;