# Generated by Django 5.2.9 on 2026-02-25 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'order_statuses',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PickUpPoint',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('post_code', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('building', models.IntegerField()),
            ],
            options={
                'db_table': 'pick_up_points',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'product_categories',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductProducer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'product_producers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductProvider',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'product_providers',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'product_units',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'roles',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('article', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('discount', models.IntegerField(default=0)),
                ('amount_in_stock', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='catalog.productcategory')),
                ('producer', models.ForeignKey(db_column='producer_id', on_delete=django.db.models.deletion.CASCADE, to='catalog.productproducer')),
                ('provider', models.ForeignKey(db_column='provider_id', on_delete=django.db.models.deletion.CASCADE, to='catalog.productprovider')),
                ('unit', models.ForeignKey(db_column='unit_id', on_delete=django.db.models.deletion.CASCADE, to='catalog.productunit')),
            ],
            options={
                'db_table': 'products',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('surname', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('patronymic', models.CharField(max_length=100)),
                ('login', models.CharField(max_length=100, unique=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('user_role', models.ForeignKey(db_column='user_role', on_delete=django.db.models.deletion.CASCADE, to='catalog.role')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateField()),
                ('date_delivery', models.DateField()),
                ('receipt_code', models.IntegerField()),
                ('status', models.ForeignKey(db_column='status_id', on_delete=django.db.models.deletion.CASCADE, to='catalog.orderstatus')),
                ('pick_up_point', models.ForeignKey(db_column='pick_up_point_id', on_delete=django.db.models.deletion.CASCADE, to='catalog.pickuppoint')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='catalog.user')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ProductInOrder',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('order', models.ForeignKey(db_column='order_id', on_delete=django.db.models.deletion.CASCADE, to='catalog.order')),
                ('product', models.ForeignKey(db_column='product_id', on_delete=django.db.models.deletion.CASCADE, to='catalog.product')),
            ],
            options={
                'db_table': 'product_in_order',
                'ordering': ['id'],
                'unique_together': {('order', 'product')},
            },
        ),
    ]
